development:
  host: localhost
  database: govuk_needs_development
  allow_dynamic_fields: false
  persist_in_safe_mode: true
test:
  host: localhost
  database: govuk_needs_test
  allow_dynamic_fields: false
  persist_in_safe_mode: true
